export type DevThemePreset = {
  name: string;
  variables: Record<string, string>;
};

export const devThemePresets: DevThemePreset[] = [
  {
    name: "DAYIIIatch Classic",
    variables: {
      "--ds-page-max-width": "1280px",
      "--ds-section-gap": "48px",
      "--ds-bg-image": "/bg-main.png",
      "--ds-bg-overlay-opacity": "0",
      "--ds-accent": "#22d3ee",
      "--ds-home-hero-width": "min(90rem, calc(100vw - 0.35rem))",
      "--ds-home-hero-height": "360px",
      "--ds-home-hero-object-fit": "cover",
      "--ds-home-hero-object-position-x": "center",
      "--ds-home-hero-object-position-y": "center",
      "--ds-nav-gap": "8px",
      "--ds-sticky-cta-bottom": "20px",
      "--ds-v11-about-max-width": "1280px",
      "--ds-v11-about-padding": "32px",
      "--ds-v11-about-heading": "#ffffff",
      "--ds-v11-about-body": "#cbd5e1",
      "--ds-v11-about-card-bg": "#071220",
      "--ds-v11-about-radius": "32px",
      "--ds-v11-proof-card-gap": "16px",
      "--ds-v11-proof-card-radius": "28px",
      "--ds-v11-proof-card-bg": "#071220",
      "--ds-v11-proof-card-border": "#22d3ee",
      "--ds-v11-proof-glow-strength": "44px",
      "--ds-v11-service-card-gap": "16px",
      "--ds-v11-service-card-radius": "24px",
      "--ds-v11-service-card-bg": "#071220",
      "--ds-v11-service-card-border": "#22d3ee",
      "--ds-v11-service-button-radius": "16px",
      "--ds-v11-footer-padding": "32px",
      "--ds-v11-footer-text": "#94a3b8",
      "--ds-v11-footer-link": "#cbd5e1",
      "--ds-v11-footer-link-gap": "8px",
    },
  },
  {
    name: "DAYIIIatch Neon",
    variables: {
      "--ds-accent": "#00f5ff",
      "--ds-bg-overlay-opacity": "0.1",
      "--ds-home-hero-height": "390px",
      "--ds-nav-gap": "12px",
      "--ds-v11-about-card-bg": "#04111f",
      "--ds-v11-proof-card-bg": "#04111f",
      "--ds-v11-proof-card-border": "#00f5ff",
      "--ds-v11-proof-glow-strength": "70px",
      "--ds-v11-service-card-bg": "#061327",
      "--ds-v11-service-card-border": "#8b5cf6",
      "--ds-v11-footer-link": "#67e8f9",
    },
  },
  {
    name: "GhostDock",
    variables: {
      "--ds-accent": "#e2e8f0",
      "--ds-bg-overlay-opacity": "0.16",
      "--ds-section-gap": "40px",
      "--ds-home-hero-height": "330px",
      "--ds-v11-about-card-bg": "#111827",
      "--ds-v11-about-heading": "#f8fafc",
      "--ds-v11-about-body": "#d1d5db",
      "--ds-v11-proof-card-bg": "#101624",
      "--ds-v11-proof-card-border": "#94a3b8",
      "--ds-v11-service-card-bg": "#111827",
      "--ds-v11-service-card-border": "#64748b",
      "--ds-v11-footer-text": "#9ca3af",
      "--ds-v11-footer-link": "#f8fafc",
    },
  },
  {
    name: "Project Damarko",
    variables: {
      "--ds-accent": "#a855f7",
      "--ds-bg-overlay-opacity": "0.08",
      "--ds-home-hero-height": "380px",
      "--ds-home-hero-object-position-y": "center",
      "--ds-v11-about-card-bg": "#10091d",
      "--ds-v11-about-heading": "#f5d0fe",
      "--ds-v11-about-body": "#ddd6fe",
      "--ds-v11-proof-card-border": "#a855f7",
      "--ds-v11-proof-glow-strength": "64px",
      "--ds-v11-service-card-bg": "#120a24",
      "--ds-v11-service-card-border": "#22d3ee",
      "--ds-v11-service-button-radius": "22px",
      "--ds-v11-footer-link": "#d8b4fe",
    },
  },
  {
    name: "EchoForge",
    variables: {
      "--ds-accent": "#10b981",
      "--ds-bg-overlay-opacity": "0.12",
      "--ds-section-gap": "44px",
      "--ds-home-hero-height": "350px",
      "--ds-v11-about-card-bg": "#041714",
      "--ds-v11-about-heading": "#d1fae5",
      "--ds-v11-about-body": "#a7f3d0",
      "--ds-v11-proof-card-bg": "#041714",
      "--ds-v11-proof-card-border": "#10b981",
      "--ds-v11-proof-glow-strength": "58px",
      "--ds-v11-service-card-bg": "#05231c",
      "--ds-v11-service-card-border": "#34d399",
      "--ds-v11-footer-link": "#6ee7b7",
    },
  },
  {
    name: "Clean Light Lab",
    variables: {
      "--ds-accent": "#0284c7",
      "--ds-bg-overlay-opacity": "0.02",
      "--ds-section-gap": "36px",
      "--ds-home-hero-height": "320px",
      "--ds-v11-about-card-bg": "#f8fafc",
      "--ds-v11-about-heading": "#0f172a",
      "--ds-v11-about-body": "#334155",
      "--ds-v11-proof-card-bg": "#ffffff",
      "--ds-v11-proof-card-border": "#38bdf8",
      "--ds-v11-proof-glow-strength": "30px",
      "--ds-v11-service-card-bg": "#ffffff",
      "--ds-v11-service-card-border": "#bae6fd",
      "--ds-v11-footer-text": "#475569",
      "--ds-v11-footer-link": "#075985",
    },
  },
];

export const defaultThemePreset = devThemePresets[0];

